@startuml

class Student {
    +ID: int
    +Nom: String
    +Prénom: String
    +password: String
    +StudentNumber: int
}

class Book {
    +Titre: String
    +Auteur: String
    +ISBN: String
    +Disponible: boolean
}

class Loan {
    +ID: int
    +datePret: Date
    +dateRetour: Date
    +Student: Student
    +Book: Book
}

class Librarian {
    +ID: int
    +Nom: String
    +Prénom: String
}

Student --o Loan
Book --o Loan
Librarian --o Loan

@enduml
