@startuml




state IHMLogin {

state dashboardStudent
state dashboardAdmin
state Connexion

 [*] --> Connexion: Démarrage
 Connexion --> dashboardAdmin : Connexion Admin
 Connexion --> dashboardStudent : Connexion Adherent
  }

state dashboardAdmin {

state VoirTouslesEmprunts
state HistoriqueEmprunts
state AjouterMembre
state SupprimerMembre
state AjouterLivre
state SupprimerLivre
state VoirTousLesMembres
state seDeconnecter

[*] --> VoirTouslesEmprunts
[*] --> HistoriqueEmprunts
[*] --> AjouterMembre
[*] --> SupprimerMembre
[*] --> AjouterLivre
[*] --> SupprimerLivre
[*] --> VoirTousLesMembres
[*] --> VoirtouslesLivres
[*] --> seDeconnecter

}

state dashboardStudent {

state VoirLivresDisponibles
state Emprunter
state Retourner
state VoirTouslesLivres
state VoirMesEmprunts
state SeDeconnecter

[*] --> VoirMesEmprunts
[*] --> VoirLivresDisponibles
[*] --> Emprunter
[*] --> Retourner
[*] -->VoirTouslesLivres
[*] --> SeDeconnecter


@enduml
